### ISSUE TITLE
The RegionYolo layer is not yet implemented.

### ISSUE THREAD

**Issue by semihstp** [PINTO0309/openvino2tensorflow#10]
Hi! I'm trying to convert my custom yolov4.weights file to tflite.
Yolov4.weights -> openvino(.bin, .xml) -> tflite.
But this error occured.

"The RegionYolo layer is not yet implemented."

![Ekran Görüntüsü (1012)](https://user-images.githubusercontent.com/56072259/104091475-a6ab2600-528e-11eb-837a-d8d4f296dcf9.png)

Can @PINTO0309 help me with my problem? It's relevant my graduate project. So
if you help me with my problem I would be very pleased.

**Comment by PINTO0309** [comment]
It is not practical to reimplement **`RegionYolo`** in TensorFlow. So let me ask you a few questions in order to find a solution.
1. Is it a requirement to train with Darknet? Many YoloV4 implementations of frameworks other than Darknet, such as PyTorch and TensorFlow, have been released.
2. Can you try DW2TF? **https://github.com/jinyu121/DW2TF**
3. Can you try tensorflow-yolov4-tflite? **https://github.com/hunglc007/tensorflow-yolov4-tflite**
4. Does your YoloV4 model have any special customization against the official model?

**Comment by semihstp** [comment]
Yes i have to train with Yolov4. The project about an android detection app based on yolov4 and Tensorflow Lite. 
I have tried the 2 and 3 repositories but converted tflite files has almost 250MB. So i cant use them on the app. When i saw your repo and gifs, i saw that your tflite size 3-5MB like i want to convert. 

I didint any change yolov4 model. Just train my own dataset and classes. I have 32 classes in this case.

**Comment by PINTO0309** [comment]
Uh... For the smaller model, I use the ultra-light version called **`YoloV4-tiny`**. The 250MB size YoloV4 is the **`full size YoloV4`**. As expected, it is impossible to compress a 250MB model to 2-3MB.
**https://github.com/PINTO0309/PINTO_model_zoo/tree/master/046_yolov4-tiny**

I used the following repository.
**https://github.com/bubbliiiing/yolov4-tiny-keras.git**

**Comment by semihstp** [comment]
Okey. I will try to do training on yolov4-tiny model and then i will convert .tflite. Thanks for your advice :)
