### ISSUE TITLE
OpenVINO MobileNetV2 model conversion

### ISSUE THREAD

**Issue by Semen52** [PINTO0309/openvino2tensorflow#12]
Hi,

Could you please with the following sample? https://docs.openvinotoolkit.org/2021.2/omz_models_intel_person_vehicle_bike_detection_2002_description_person_vehicle_bike_detection_2002.html

Is is possible to convert?

>  python3 openvino2tensorflow.py --model_path=tmp/FP32/person-vehicle-bike-detection-2002.xml --output_saved_model True --output_pb True
Output:
/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py:22: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
The PriorBoxClustered layer is not yet implemented.

**Comment by PINTO0309** [comment]
Unfortunately, this model cannot be converted because **`PriorBoxClustered`** is not replaceable with standard TensorFlow OPs.

**Comment by Semen52** [comment]
Thanks.
Do you have a full list of supported OV models? I see _10. Conversion Confirmed Models_.

**Comment by PINTO0309** [comment]
Most of the models committed here can be converted. Rather, it has been converted. However, I have been experimenting with conversions little by little for over a year now, and I believe that there are some models that will not work due to changes in the framework version.
**https://github.com/PINTO0309/PINTO_model_zoo**

**Comment by Semen52** [comment]
Thank you very much. I will close the issue then.
