### ISSUE TITLE
Incorrect connection order in Concat

### ISSUE THREAD

**Issue by PINTO0309** [PINTO0309/openvino2tensorflow#48]
#### 10. Download URL for OpenVINO IR (.bin/.xml) model
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/132_YOLOX
#### 11. URL of the repository from which the transformed model was taken:
https://github.com/PINTO0309/PINTO_model_zoo/tree/main/132_YOLOX
#### 13. Issue Details
In models such as YOLOv5, YOLOR, and YOLOX, the connection order of input layers is different when the starting point is concat via multiple StridedSlices. Therefore, even if the structure of the intermediate layer is correctly converted, the data at the input will be corrupted, and the output result will be meaningless. The order of tensor decomposition and the order of concatenation by Concat need to be controlled correctly.

- ONNX (Before conversion)
![Screenshot 2021-07-28 14:00:21](https://user-images.githubusercontent.com/33194443/127266360-5e7a556c-d25a-4d44-9447-5da3f9c00f09.png)

- TFLite (openvino2tensorflow / after conversion)
![Screenshot 2021-07-28 13:58:58](https://user-images.githubusercontent.com/33194443/127266257-824d7404-235f-41ef-93cd-6b2c40e5e2cb.png)

- TFLite (onnx-tensorflow / after convertion)
![Screenshot 2021-07-28 14:09:11](https://user-images.githubusercontent.com/33194443/127267217-9e839a11-f519-4604-a790-368fa7b8e4c4.png)

**Comment by NobuoTsukamoto** [comment]
If my understanding is correct,
As far as YOLOX is concerned, the Strided Slice of the input layer has the same parameters. Therefore, it seems that there is no effect even if the order is different.

The problem seems to be with Concat in the middle layer. 
- There are two in YOLOX 320X320.
- Both have resizing in one of the Opes.

The following is one of them.
OpenVINO model
![Screenshot from 2021-07-30 20-14-15](https://user-images.githubusercontent.com/17954673/127645966-de4aea90-310b-4616-adea-d9dd0f381b51.png)

TensorFlow Lite model. Although it is shown in red, the order of Concat is different between the OpenVINO model and the TensorFlow Lite model.
![Screenshot from 2021-07-30 20-15-55](https://user-images.githubusercontent.com/17954673/127646106-2240f4cd-5edf-4023-ba12-a055de60dc08.png)

In the case of a concatenate like Skip connection like U-Net, it seems to be because the id of input and the actual order are reversed.

**Comment by PINTO0309** [comment]
@NobuoTsukamoto Thank you for your support! :smile_cat: 

Well, you have a point. However, I am very worried about how to fix it. The only way I can think of is to sort the layer IDs entered in the INPUT of OpenVINO's Concat in ascending order and then Concat them. However, since OpenVINO often reverses the order of operations displayed in INPUT and sometimes not, I am not sure if this fix will work for all models.

Anyway, I'm going to apply the workaround, regenerate the model, and provide the tflite model to you again.

**Comment by PINTO0309** [comment]
This is a part of the log of the tflite conversion process of concat. The assumption was the exact opposite. When importing openvino concat layers, the layer IDs were sorted in ascending order. I may need to modify it to accept the order as it is, without sorting.
![Screenshot 2021-07-30 23:18:44](https://user-images.githubusercontent.com/33194443/127666750-65014ff2-ad48-45da-99da-ac4736e834e4.png)

**Comment by PINTO0309** [comment]
However, the xml file is connected to concat in the order of this image. In other words, the conversion behavior to tflite appears to be working correctly. "304" = Concat, "228" = Mul, "303" = Interporate
![Screenshot 2021-07-30 23:27:15](https://user-images.githubusercontent.com/33194443/127667852-ee4b9938-5a4d-46bd-8571-5627c384112f.png)
![Screenshot 2021-07-30 23:27:34](https://user-images.githubusercontent.com/33194443/127667864-0dad8db9-96dd-4d2c-b87d-38d6887de7b9.png)

**Comment by PINTO0309** [comment]
I understand. The port numbers are reversed.

**Comment by PINTO0309** [comment]
Fixes f037817dcaeebe9208293dd598d93f39d7d13602
