### ISSUE TITLE
Output result doesn't match between IR and TFLite

### ISSUE THREAD

**Issue by YenchungChen** [PINTO0309/openvino2tensorflow#64]
#### 6. Issue Details

I'm converting an identical model mentioned in this [closed issue](https://github.com/PINTO0309/openvino2tensorflow/issues/20).
The issue above is solved and the [converted model](https://github.com/PINTO0309/PINTO_model_zoo/tree/main/091_gaze-estimation-adas-0002) from PINTO_model_zoo works fine.

Although the correct converted model is provided by author in the above link, I tried to convert it through openvion2tensorflow.
Following are the visualization of the IR model (.xml) and the corresponding TFLite model (converted by openvino2tensorflow):
 **IR model**
<img width="512" alt="gaze_xml" src="https://user-images.githubusercontent.com/14832800/129502621-01ca1ceb-b7ff-4f58-a7bf-c49341d1ca57.png">

**TFLite model**
<img width="512" alt="gaze_tflite_b4correct" src="https://user-images.githubusercontent.com/14832800/129502648-f585a02b-9a24-46ac-8bf3-96f40789b897.png">

The output shape of StridedSlice in TFLite model is (1, 1, 1).

**Comment by PINTO0309** [comment]
The slice position is misaligned because it is difficult to mechanically identify the axis of a 3D slice. This is a specification of the tool. 

There are two ways to solve this problem.
1. How to process .xml by hand to remove unwanted layers and optimize the model
2. How to correct the Const value of the axis of StridedSlice according to the following explanation. https://github.com/PINTO0309/openvino2tensorflow#6-7-replace-weights-or-constant-values-in-const-op-and-add-transpose-or-reshape-just-before-the-operation-specified-by-layer_id

Depending on the complexity of the model structure, you can choose the simpler of the above two. Since this issue is likely to be simple, requiring only the deletion of a few layers at the end of the model, I will show the steps for 1.

The red frame in the figure below is almost a pointless process, so I manually processed the XML file and removed it. Please compare **`gaze-estimation-adas-0002.xml`** and **`gaze-estimation-adas-0002_org.xml`** to see how to edit them. You can easily optimize the structure by simply modifying the connection information between layers.
- Structure of the XML file before editing (gaze-estimation-adas-0002_org.xml)
![Screenshot 2021-08-16 11:40:01](https://user-images.githubusercontent.com/33194443/129504499-814727ea-cacf-42c4-b599-69aea8336014.png)


![Screenshot 2021-08-16 11:48:08](https://user-images.githubusercontent.com/33194443/129504997-b738d628-7f0f-4244-8fd9-5353e609cf1f.png)
　：
![Screenshot 2021-08-16 11:49:42](https://user-images.githubusercontent.com/33194443/129505074-f6fe6957-b785-47a2-a4a3-bb63ca46b455.png)
![Screenshot 2021-08-16 11:51:12](https://user-images.githubusercontent.com/33194443/129505168-180f11d9-6358-4924-80bb-7bbeb3631073.png)


- Structure of the XML file after editing (gaze-estimation-adas-0002.xml)
![Screenshot 2021-08-16 11:46:04](https://user-images.githubusercontent.com/33194443/129504772-e3cd039a-d10c-47de-9bf2-bd8baad65463.png)

- Structure of tflite after conversion (from gaze-estimation-adas-0002.xml)
![Screenshot 2021-08-16 11:40:29](https://user-images.githubusercontent.com/33194443/129504366-63e1d70b-3f68-464a-ad4a-46cecc79d75d.png)

**Comment by YenchungChen** [comment]
I've exercised both ways and they work like magic.
Really appreciate for the fast reply and clear explanation.
Hope everyone enjoys this tool as much as I do.
